version: '3.4'

services:
  bankservice:
    build: ./BankService
    ports:
        - "4003:80"
    restart: always

  onboardingservice:
    build: ./OnBoardingService
    ports:
        - "4000:80"
    restart: always

  otpservice:
    build: ./OTPService
    ports:
        - "4001:80"
    restart: always
    depends_on:
      - "onboardingservice"
      - "rabbitmq"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"